# official tutorial
# mkdocs-material: https://squidfunk.github.io/mkdocs-material/
# mkdocs: https://www.mkdocs.org/user-guide/configuration/

site_name: Anu Shibin's Pastebin
theme:
    name: material
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: black
          accent: white
          toggle:
              icon: material/weather-sunny
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: black
          accent: white
          toggle:
              icon: material/weather-night
              name: Switch to light mode
    language: en
    features:
        - content.code.copy

# Extensions
markdown_extensions:
    - footnotes
    - attr_list
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.magiclink
    - pymdownx.tasklist
    - pymdownx.emoji
    - admonition
    - toc:
          permalink: true

extra:
  analytics:
    provider: google
    property: G-43TC5FZL01

plugins:
    - search
    - roamlinks
#    - encryptcontent:
#        remember_password: True
#        global_password: 'password'
